// USERS
export const AUTH_USER = "AUTH_USER";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";

// PRODUCTS
export const GET_PRODUCTS_BY_AMOUNT_SOLD = "GET_PRODUCTS_BY_AMOUNT_SOLD";
export const GET_PRODUCTS_BY_DATE = "GET_PRODUCTS_BY_DATE";

// NOTIFICATIONS
export const SUCCESS_GLOBAL = "SUCCESS_GLOBAL";
export const ERROR_GLOBAL = "ERROR_GLOBAL";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
